In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('dataset.csv')

In [9]:
df.head()

,OrderID,Customer,Product,Category,Quantity,Price,City,Date
0,1,Alice,Laptop,Electronics,1,800,Bishkek,2025-01-05
1,2,Bob,Phone,Electronics,2,500,Osh,2025-01-06
2,3,Charlie,Tablet,Electronics,1,300,Bishkek,2025-01-07
3,4,Diana,Headphones,Accessories,3,50,Karakol,2025-01-07
4,5,Evan,Keyboard,Accessories,2,70,Osh,2025-01-08

In [11]:
df.columns

Index(['OrderID', 'Customer', 'Product', 'Category', 'Quantity', 'Price',
       'City', 'Date'],
      dtype='object')

In [16]:
len(df), len(df.columns)

(15, 8)

In [25]:
def get_mean(df, key):
    print(df[key].mean())
    print(df[key].min())
    print(df[key].max())
get_mean(df,'Quantity')
get_mean(df,'Price')

2.066666666666667
1
5
337.6666666666667
25
850

In [26]:
df["Total Price"] = df['Quantity']*df['Price']

In [39]:
df['Revenue'] = df['Total Price']

In [40]:
df

,OrderID,Customer,Product,Category,Quantity,Price,City,Date,Total Price,Revenue
0,1,Alice,Laptop,Electronics,1,800,Bishkek,2025-01-05,800,800
1,2,Bob,Phone,Electronics,2,500,Osh,2025-01-06,1000,1000
2,3,Charlie,Tablet,Electronics,1,300,Bishkek,2025-01-07,300,300
3,4,Diana,Headphones,Accessories,3,50,Karakol,2025-01-07,150,150
4,5,Evan,Keyboard,Accessories,2,70,Osh,2025-01-08,140,140
5,6,Fiona,Mouse,Accessories,5,25,Bishkek,2025-01-09,125,125
6,7,George,Laptop,Electronics,1,850,Osh,2025-01-10,850,850
7,8,Helen,Phone,Electronics,1,520,Karakol,2025-01-10,520,520
8,9,Ian,Tablet,Electronics,2,310,Bishkek,2025-01-11,620,620
9,10,Jane,Monitor,Electronics,1,200,Osh,2025-01-12,200,200
10,11,Kevin,Mouse,Accessories,4,25,Bishkek,2025-01-12,100,100
11,12,Lisa,Keyboard,Accessories,1,70,Karakol,2025-01-13,70,70
12,13,Mike,Laptop,Electronics,2,780,Bishkek,2025-01-14,1560,1560
13,14,Nina,Phone,Electronics,3,510,Osh,2025-01-14,1530,1530
14,15,Omar,Headphones,Accessories,2,55,Bishkek,2025-01-15,110,110

In [28]:
df['Total Price'].sum()

8075

In [33]:
df['Total Price'].mean()

538.3333333333334

In [32]:
df['Total Price'].max()

1560

In [50]:
df.groupby('City')['Revenue'].sum().sort_values(ascending=False).head()

City
Osh        3720
Bishkek    3615
Karakol     740
Name: Revenue, dtype: int64

In [54]:
df.groupby('Product')['OrderID'].count()

Product
Headphones    2
Keyboard      2
Laptop        3
Monitor       1
Mouse         2
Phone         3
Tablet        2
Name: OrderID, dtype: int64

In [56]:
df.groupby('Customer')['Revenue'].sum().sort_values(ascending=False)

Customer
Mike       1560
Nina       1530
Bob        1000
George      850
Alice       800
Ian         620
Helen       520
Charlie     300
Jane        200
Diana       150
Evan        140
Fiona       125
Omar        110
Kevin       100
Lisa         70
Name: Revenue, dtype: int64

In [58]:
df.sort_values(by='Total Price', ascending=False)

,OrderID,Customer,Product,Category,Quantity,Price,City,Date,Total Price,Revenue
12,13,Mike,Laptop,Electronics,2,780,Bishkek,2025-01-14,1560,1560
13,14,Nina,Phone,Electronics,3,510,Osh,2025-01-14,1530,1530
1,2,Bob,Phone,Electronics,2,500,Osh,2025-01-06,1000,1000
6,7,George,Laptop,Electronics,1,850,Osh,2025-01-10,850,850
0,1,Alice,Laptop,Electronics,1,800,Bishkek,2025-01-05,800,800
8,9,Ian,Tablet,Electronics,2,310,Bishkek,2025-01-11,620,620
7,8,Helen,Phone,Electronics,1,520,Karakol,2025-01-10,520,520
2,3,Charlie,Tablet,Electronics,1,300,Bishkek,2025-01-07,300,300
9,10,Jane,Monitor,Electronics,1,200,Osh,2025-01-12,200,200
3,4,Diana,Headphones,Accessories,3,50,Karakol,2025-01-07,150,150
4,5,Evan,Keyboard,Accessories,2,70,Osh,2025-01-08,140,140
5,6,Fiona,Mouse,Accessories,5,25,Bishkek,2025-01-09,125,125
14,15,Omar,Headphones,Accessories,2,55,Bishkek,2025-01-15,110,110
10,11,Kevin,Mouse,Accessories,4,25,Bishkek,2025-01-12,100,100
11,12,Lisa,Keyboard,Accessories,1,70,Karakol,2025-01-13,70,70

In [1]:
mn = df['Price'].mean()
print(mn)
print()
print(sorted(list(df['Price'])))
mn_np=np.std(df['Price'])
print(mn_np)

NameError: name 'df' is not defined